/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.matrix;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        Matrix a = new MatrixBuilder().dimensions(3, 2)
                .addElements(2, 4, 3, 5, -4, -7, -5, -8, 6, 8, 2, 9, 4, 9, -2, 14, 43, 45, 3, 2, 54, 23, 54, 54, 23, 67,
                        43, 23, 4, 23)
                .build();

        Matrix b = new MatrixBuilder().dimensions(3, 2).addElements(3, 4, -5, -5, 3, 5, 4).build();
        // Matrix aT = a.transpose();
        Matrix c = new MatrixBuilder().dimensions(3, 2).addColumns(0, 43, 43, 2, 43, 23, 43)
                .addColumns(1, 47, 23, 43, 2, 43, 3, 3).build();
        // System.out.println("---");
        // aT.showMatrix();

        // Matrix d = b.addMatrix(a).subtractMatrix(c);

        // d.showMatrix();
        // Matrix k = d.multiplyBy(3.1).transpose();
        // k.showMatrix();
        // k.decompose();

        // k.showLU();
        Matrix one = new MatrixBuilder().dimensions(3, 2).addElements(1, 2, 3, 4, 5, 6, 7, 8, 9, 20).build();
        // one.addElement(2, 1, 13);
        Matrix two = new MatrixBuilder().dimensions(2, 3).addElements(7, 8, 9, 4, 5,
                6).build();
        one.showMatrix();
        System.out.println();
        two.showMatrix();
        Matrix t = one.dotProduct(two);
        // t.showMatrix();
        // two.dotProduct(one);
        // three.showMatrix();

    }
}
